CREATE OR REPLACE TRIGGER DESPEDIR_EMPLEADO
BEFORE 
DELETE ON EMPLOYEES 
FOR EACH ROW
BEGIN 

    INSERT INTO JOB_HISTORY(
        EMPLOYEE_ID,
        START_DATE,
        END_DATE,
        JOB_ID,
        DEPARTMENT_ID
    )VALUES(
        :OLD.EMPLOYEE_ID,
        :OLD.HIRE_DATE,
        SYSDATE,
        :OLD.JOB_ID,
        :OLD.DEPARTMENT_ID
    )
END;


DELETE FROM EMPLOYEES WHERE EMPLOYEE_ID IN (105, 200, 100, 108);


